[package]
name = "pokemon_escape_server"
license = "GPL-3.0-or-later"
repository = "https://github.com/Kloenk/pokemon_escape_server"
version = "0.1.0"
authors = ["Finn Behrens <me@kloenk.de>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
colored = "1.7.0"